from fastapi import FastAPI
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel
from llm.main import generate_explanation, initialize_ollama

app = FastAPI()

# Decent config for production
app.add_middleware(
    CORSMiddleware,
    allow_origins=[
        "tauri://localhost",        # macOS/Linux production
        "http://tauri.localhost",   # Windows production (WebView2)
        "https://tauri.localhost",  # some WebView2 configs use https
        "http://localhost:1420",    # dev server
    ],
    allow_methods=["POST", "GET"],
    allow_headers=["*"],
)

# Prototyping middleware
# app.add_middleware(
#     CORSMiddleware,
#     allow_origins=["*"],
#     allow_methods=["*"],
#     allow_headers=["*"],
# )

SYSTEM_PROMPT = (
    "You are an educational financial literacy assistant. "
    "You explain financial concepts clearly, but you do not give "
    "personalized investment, tax, or legal advice, and you do not "
    "recommend specific securities yourself. "
    "Sometimes you will be given a recommendation generated by a separate "
    "reinforcement-learning trading model (ticker, action, confidence, and "
    "the features that influenced it) — in that case, explain why the model "
    "likely produced that output and what the confidence score does and "
    "doesn't mean, without endorsing or evaluating whether the user should "
    "act on it. Always note that this is educational content, not "
    "professional financial advice."
)

class ChatRequest(BaseModel):
    message: str

class ChatResponse(BaseModel):
    reply: str


def generate_reply(message: str) -> str:
    print(f"Received message: {message} - generating recommendation text")

    explanation_list = generate_explanation("recommendations.json")

    if len(explanation_list) == 0:
        return "Failed to generate explanation list"

    for e in explanation_list:
        print(f"{e['ticker']}: {e['action']} ({e['justification']})")

    formatted_reply = "\n\n".join(
        f"**{e['ticker']}** ({e['action']}): {e['justification']}"
        for e in explanation_list
    )

    return formatted_reply

@app.get("/health")
def health():
    return {"status": "ok"}

@app.post("/chat", response_model=ChatResponse)
def chat(req: ChatRequest):
    reply = generate_reply(req.message)
    return ChatResponse(reply=reply)

if __name__ == "__main__":
    import uvicorn
    initialize_ollama()
    uvicorn.run(app, host="127.0.0.1", port=8721)
