import json
from pathlib import Path
from typing import List, Optional, Union, Any

from rl_pipeline.main import JsonRecommendation
from config import OUTPUT_DIR

RECOMMENDATIONS_FILE = "recommendations.json"


def load_recommendations(filename: str = RECOMMENDATIONS_FILE) -> dict[str, Any]:
    """Loads the latest evaluation payload generated by the RL pipeline."""
    path = OUTPUT_DIR / filename

    if not path.exists():
        raise FileNotFoundError(
            f"No recommendations found at {path}. Run an evaluation first."
        )

    with open(path, "r") as f:
        data: dict[str, Any] = json.load(f)
        return data


def generate_quiz(recs: JsonRecommendation | None = None) -> list[dict[str, str | list[str]]]:
    """
    Builds a quiz from the RL agent's output.

    The questions are derived from the recommendations payload so that the
    review step can regenerate the same questions (and correct answers)
    server-side without trusting the client.
    """
    if recs is None:
        recs = load_recommendations()

    allocations = recs.get("allocations", [])
    summary = recs.get("backtest_summary", {})

    questions: list[dict[str, str | list[str]]] = []

    # One question per top allocation (capped to keep the quiz short).o
    for i, alloc in enumerate(allocations[:3]):
        ticker = alloc.get("ticker")
        action = alloc.get("action")

        questions.append({
            "id": f"action-{i}",
            "type": "mcq",
            "question": f"Which action did the RL agent recommend for {ticker}?",
            "options": ["BUY", "SELL", "HOLD"],
            "correct": action,
        })

    # Benchmark comparison question.
    rl_ret = summary.get("rl_return_pct", 0)
    bh_ret = summary.get("bh_return_pct", 0)

    if rl_ret > bh_ret:
        correct = "Outperformed"
    elif rl_ret < bh_ret:
        correct = "Underperformed"
    else:
        correct = "Roughly equal"

    questions.append({
        "id": "benchmark",
        "type": "mcq",
        "question": (
            "Over the evaluation period, how did the RL agent compare to a "
            "simple buy-and-hold benchmark?"
        ),
        "options": ["Outperformed", "Underperformed", "Roughly equal"],
        "correct": correct,
    })

    # Open-ended analysis question about the highest-weighted allocation.
    if allocations:
        top = allocations[0]
        ticker = top.get("ticker")
        action = top.get("action")

        questions.append({
            "id": "analysis-0",
            "type": "open",
            "question": (
                f"In your own words, why might the agent have recommended "
                f"{action} for {ticker}?"
            ),
            "context": (
                f"{ticker}: RSI {top.get('rsi')}, MACD histogram "
                f"{top.get('macd_hist')}, Bollinger Band % {top.get('bb_pct')}, "
                f"{top.get('pct_of_budget')}% of the budget."
            ),
        })

    return questions


def strip_correct_answers(questions: List[dict]) -> List[dict]:
    """Removes the `correct` field so answers are not leaked to the client."""
    return [
        {k: v for k, v in q.items() if k != "correct"}
        for q in questions
    ]


def build_review_prompt(questions: List[dict], answers: List[dict]) -> str:
    """Formats the quiz, correct answers, and user answers for the LLM."""
    answer_map = {
        a.get("question_id"): a.get("answer", "")
        for a in answers
    }

    blocks = []
    for q in questions:
        blocks.append({
            "id": q.get("id"),
            "type": q.get("type"),
            "question": q.get("question"),
            "options": q.get("options"),
            "correct_answer": q.get("correct"),
            "user_answer": answer_map.get(q.get("id"), "(no answer)"),
        })

    return json.dumps(blocks, indent=2, ensure_ascii=False)
